import type { CuisineCountry, CuisineRegion } from "@/types/cuisine";

export const CUISINE_COUNTRIES: CuisineCountry[] = [
  // ─── Americas ───────────────────────────────────────────────
  {
    id: "mexico",
    name: "Mexico",
    flag: "🇲🇽",
    region: "americas",
    typicalIngredients: [
      "corn tortillas",
      "black beans",
      "avocado",
      "chili peppers",
      "lime",
      "cilantro",
      "tomato",
      "onion",
      "queso fresco",
      "chicken",
      "rice",
      "nopales",
    ],
    mealPatterns: {
      breakfast: [
        "Chilaquiles verdes",
        "Huevos rancheros",
        "Molletes con frijoles",
        "Tamales con atole",
      ],
      lunch: [
        "Tacos al pastor",
        "Pozole rojo",
        "Enchiladas suizas",
        "Sopa de tortilla",
      ],
      dinner: [
        "Quesadillas de pollo",
        "Tostadas de tinga",
        "Flautas con guacamole",
      ],
      snack: [
        "Elote con mayonesa y chile",
        "Guacamole con totopos",
        "Fruta con tajín",
      ],
    },
  },
  {
    id: "colombia",
    name: "Colombia",
    flag: "🇨🇴",
    region: "americas",
    typicalIngredients: [
      "arepa flour",
      "plantain",
      "rice",
      "black beans",
      "avocado",
      "chicken",
      "beef",
      "potato",
      "yuca",
      "hogao sauce",
      "panela",
      "corn",
    ],
    mealPatterns: {
      breakfast: [
        "Arepa con huevo y queso",
        "Calentado con arroz y frijoles",
        "Changua (caldo de huevo)",
        "Empanadas con ají",
      ],
      lunch: [
        "Bandeja paisa",
        "Ajiaco santafereño",
        "Sancocho de gallina",
        "Arroz con pollo",
      ],
      dinner: [
        "Patacones con hogao",
        "Tamales tolimenses",
        "Cazuela de frijoles",
      ],
      snack: [
        "Buñuelos",
        "Pandebono",
        "Obleas con arequipe",
      ],
    },
  },
  {
    id: "argentina",
    name: "Argentina",
    flag: "🇦🇷",
    region: "americas",
    typicalIngredients: [
      "beef",
      "chimichurri",
      "empanada dough",
      "dulce de leche",
      "mozzarella",
      "onion",
      "red pepper",
      "potato",
      "wheat flour",
      "eggs",
      "yerba mate",
      "chorizo",
    ],
    mealPatterns: {
      breakfast: [
        "Medialunas con café",
        "Tostadas con dulce de leche",
        "Mate con bizcochitos",
      ],
      lunch: [
        "Asado con chimichurri",
        "Milanesa napolitana con puré",
        "Empanadas de carne",
        "Locro",
      ],
      dinner: [
        "Bife de chorizo con ensalada",
        "Pizza argentina",
        "Ñoquis con tuco",
      ],
      snack: [
        "Alfajores de maicena",
        "Facturas surtidas",
        "Mate con tortas fritas",
      ],
    },
  },
  {
    id: "peru",
    name: "Peru",
    flag: "🇵🇪",
    region: "americas",
    typicalIngredients: [
      "ají amarillo",
      "lime",
      "fish",
      "potato",
      "corn",
      "quinoa",
      "rice",
      "chicken",
      "red onion",
      "cilantro",
      "sweet potato",
      "garlic",
    ],
    mealPatterns: {
      breakfast: [
        "Pan con chicharrón",
        "Quinoa con leche",
        "Tamales verdes",
      ],
      lunch: [
        "Ceviche clásico",
        "Lomo saltado",
        "Ají de gallina",
        "Arroz con pollo",
      ],
      dinner: [
        "Causa limeña",
        "Seco de res con frijoles",
        "Tacu tacu con lomo",
      ],
      snack: [
        "Picarones con miel de chancaca",
        "Choclo con queso",
        "Anticuchos de corazón",
      ],
    },
  },
  {
    id: "brazil",
    name: "Brazil",
    flag: "🇧🇷",
    region: "americas",
    typicalIngredients: [
      "black beans",
      "rice",
      "cassava",
      "chicken",
      "beef",
      "palm oil (dendê)",
      "coconut milk",
      "garlic",
      "onion",
      "tomato",
      "farofa",
      "lime",
    ],
    mealPatterns: {
      breakfast: [
        "Pão de queijo",
        "Açaí bowl com granola",
        "Tapioca com queijo e presunto",
        "Café com leite e pão na chapa",
      ],
      lunch: [
        "Feijoada completa",
        "Frango com quiabo",
        "Moqueca de peixe",
        "Arroz, feijão e bife acebolado",
      ],
      dinner: [
        "Coxinha de frango",
        "Escondidinho de carne seca",
        "Strogonoff de frango com arroz",
      ],
      snack: [
        "Pastel de feira",
        "Brigadeiro",
        "Pão de queijo",
      ],
    },
  },
  {
    id: "usa",
    name: "United States",
    flag: "🇺🇸",
    region: "americas",
    typicalIngredients: [
      "chicken breast",
      "ground beef",
      "eggs",
      "cheddar cheese",
      "bread",
      "potatoes",
      "broccoli",
      "rice",
      "peanut butter",
      "oats",
      "milk",
      "bacon",
    ],
    mealPatterns: {
      breakfast: [
        "Scrambled eggs with toast",
        "Oatmeal with berries",
        "Pancakes with maple syrup",
        "Greek yogurt parfait",
      ],
      lunch: [
        "Grilled chicken salad",
        "Turkey club sandwich",
        "Chicken burrito bowl",
        "Cobb salad",
      ],
      dinner: [
        "Grilled salmon with vegetables",
        "Steak with baked potato",
        "Chicken stir-fry with rice",
        "Meatloaf with mashed potatoes",
      ],
      snack: [
        "Protein shake",
        "Trail mix",
        "Apple with peanut butter",
      ],
    },
  },

  // ─── Europe ─────────────────────────────────────────────────
  {
    id: "spain",
    name: "Spain",
    flag: "🇪🇸",
    region: "europe",
    typicalIngredients: [
      "olive oil",
      "garlic",
      "tomato",
      "onion",
      "bell pepper",
      "saffron",
      "chorizo",
      "chicken",
      "fish",
      "potatoes",
      "eggs",
      "paprika",
    ],
    mealPatterns: {
      breakfast: [
        "Tostada con tomate y aceite",
        "Churros con chocolate",
        "Tortilla española con pan",
      ],
      lunch: [
        "Paella valenciana",
        "Cocido madrileño",
        "Gazpacho andaluz",
        "Pisto manchego",
      ],
      dinner: [
        "Tortilla de patatas",
        "Pulpo a la gallega",
        "Croquetas de jamón",
        "Pimientos de padrón con huevos",
      ],
      snack: [
        "Jamón serrano con pan",
        "Aceitunas y queso manchego",
        "Patatas bravas",
      ],
    },
  },
  {
    id: "italy",
    name: "Italy",
    flag: "🇮🇹",
    region: "europe",
    typicalIngredients: [
      "pasta",
      "olive oil",
      "tomato",
      "garlic",
      "basil",
      "parmesan",
      "mozzarella",
      "chicken",
      "zucchini",
      "onion",
      "prosciutto",
      "bread",
    ],
    mealPatterns: {
      breakfast: [
        "Cornetto con cappuccino",
        "Fette biscottate con marmellata",
        "Yogurt con muesli e frutta",
      ],
      lunch: [
        "Spaghetti alla carbonara",
        "Risotto ai funghi porcini",
        "Penne all'arrabbiata",
        "Insalata caprese con pane",
      ],
      dinner: [
        "Pollo alla parmigiana",
        "Salmone al forno con verdure",
        "Minestrone di verdure",
        "Bruschetta con insalata mista",
      ],
      snack: [
        "Bruschetta al pomodoro",
        "Frutta fresca di stagione",
        "Pane con olio e origano",
      ],
    },
  },
  {
    id: "france",
    name: "France",
    flag: "🇫🇷",
    region: "europe",
    typicalIngredients: [
      "butter",
      "cream",
      "eggs",
      "chicken",
      "baguette",
      "gruyère",
      "shallots",
      "garlic",
      "thyme",
      "mushrooms",
      "white wine",
      "dijon mustard",
    ],
    mealPatterns: {
      breakfast: [
        "Croissant au beurre",
        "Tartine avec confiture",
        "Œufs brouillés aux herbes",
      ],
      lunch: [
        "Quiche lorraine avec salade",
        "Croque-monsieur",
        "Salade niçoise",
        "Poulet rôti avec légumes",
      ],
      dinner: [
        "Ratatouille provençale",
        "Saumon en papillote",
        "Soupe à l'oignon gratinée",
        "Boeuf bourguignon",
      ],
      snack: [
        "Fromage et baguette",
        "Crêpe au sucre",
        "Yaourt nature avec miel",
      ],
    },
  },
  {
    id: "germany",
    name: "Germany",
    flag: "🇩🇪",
    region: "europe",
    typicalIngredients: [
      "pork",
      "potatoes",
      "sauerkraut",
      "rye bread",
      "eggs",
      "mustard",
      "onion",
      "butter",
      "cream",
      "apple",
      "cabbage",
      "carrot",
    ],
    mealPatterns: {
      breakfast: [
        "Vollkornbrot mit Käse und Aufschnitt",
        "Müsli mit Joghurt",
        "Rührei mit Brot",
      ],
      lunch: [
        "Schnitzel mit Kartoffelsalat",
        "Bratwurst mit Sauerkraut",
        "Linseneintopf",
        "Käsespätzle mit Röstzwiebeln",
      ],
      dinner: [
        "Abendbrot (Brot, Käse, Wurst)",
        "Kartoffelsuppe",
        "Frikadellen mit Gemüse",
      ],
      snack: [
        "Brezel mit Butter",
        "Apfelstrudel",
        "Quark mit Früchten",
      ],
    },
  },
  {
    id: "uk",
    name: "United Kingdom",
    flag: "🇬🇧",
    region: "europe",
    typicalIngredients: [
      "chicken",
      "beef",
      "potatoes",
      "eggs",
      "cheddar cheese",
      "bread",
      "oats",
      "peas",
      "carrots",
      "onion",
      "butter",
      "milk",
    ],
    mealPatterns: {
      breakfast: [
        "Full English breakfast",
        "Porridge with honey",
        "Eggs Benedict",
        "Toast with marmalade",
      ],
      lunch: [
        "Fish and chips",
        "Shepherd's pie",
        "Ploughman's lunch",
        "Chicken tikka masala with rice",
      ],
      dinner: [
        "Sunday roast with Yorkshire pudding",
        "Bangers and mash",
        "Cottage pie with greens",
      ],
      snack: [
        "Scones with clotted cream",
        "Digestive biscuits",
        "Cheese and pickle sandwich",
      ],
    },
  },

  // ─── Asia ───────────────────────────────────────────────────
  {
    id: "japan",
    name: "Japan",
    flag: "🇯🇵",
    region: "asia",
    typicalIngredients: [
      "rice",
      "soy sauce",
      "tofu",
      "salmon",
      "miso",
      "seaweed",
      "eggs",
      "green onion",
      "sesame",
      "ginger",
      "chicken",
      "mirin",
    ],
    mealPatterns: {
      breakfast: [
        "Tamago kake gohan",
        "Miso soup with rice and grilled salmon",
        "Onigiri with pickles",
      ],
      lunch: [
        "Chicken katsu curry",
        "Ramen with chashu pork",
        "Salmon onigiri bento",
        "Teriyaki chicken don",
      ],
      dinner: [
        "Grilled mackerel with rice and miso soup",
        "Sukiyaki hot pot",
        "Sashimi with edamame and rice",
        "Yakitori with salad",
      ],
      snack: [
        "Edamame with sea salt",
        "Onigiri",
        "Tamagoyaki",
      ],
    },
  },
  {
    id: "china",
    name: "China",
    flag: "🇨🇳",
    region: "asia",
    typicalIngredients: [
      "rice",
      "soy sauce",
      "ginger",
      "garlic",
      "green onion",
      "tofu",
      "pork",
      "chicken",
      "sesame oil",
      "bok choy",
      "noodles",
      "chili bean paste",
    ],
    mealPatterns: {
      breakfast: [
        "Congee with century egg",
        "Jianbing (savory crepe)",
        "Steamed buns (baozi)",
        "Soy milk with fried dough sticks",
      ],
      lunch: [
        "Kung pao chicken with rice",
        "Mapo tofu with steamed rice",
        "Beef chow mein",
        "Dim sum assortment",
      ],
      dinner: [
        "Sweet and sour pork",
        "Steamed fish with ginger and scallion",
        "Hot pot with vegetables and meat",
        "Tomato egg stir-fry with rice",
      ],
      snack: [
        "Spring rolls",
        "Steamed dumplings (jiaozi)",
        "Red bean buns",
      ],
    },
  },
  {
    id: "india",
    name: "India",
    flag: "🇮🇳",
    region: "asia",
    typicalIngredients: [
      "basmati rice",
      "lentils (dal)",
      "chickpeas",
      "turmeric",
      "cumin",
      "coriander",
      "ginger",
      "garlic",
      "onion",
      "tomato",
      "yogurt",
      "ghee",
    ],
    mealPatterns: {
      breakfast: [
        "Poha with peanuts",
        "Idli with sambar and chutney",
        "Paratha with curd",
        "Upma with vegetables",
      ],
      lunch: [
        "Dal tadka with jeera rice",
        "Chicken biryani",
        "Rajma chawal",
        "Chole with bhature",
      ],
      dinner: [
        "Palak paneer with roti",
        "Butter chicken with naan",
        "Vegetable thali",
        "Fish curry with rice",
      ],
      snack: [
        "Samosa with chutney",
        "Masala chai with biscuits",
        "Chana chaat",
      ],
    },
  },
  {
    id: "thailand",
    name: "Thailand",
    flag: "🇹🇭",
    region: "asia",
    typicalIngredients: [
      "jasmine rice",
      "coconut milk",
      "lemongrass",
      "thai basil",
      "fish sauce",
      "lime",
      "chili",
      "garlic",
      "shrimp",
      "chicken",
      "tofu",
      "galangal",
    ],
    mealPatterns: {
      breakfast: [
        "Jok (rice porridge) with egg",
        "Kai jeow (Thai omelette) with rice",
        "Pa tong ko with coffee",
      ],
      lunch: [
        "Pad Thai with shrimp",
        "Green curry with chicken",
        "Tom yum goong",
        "Khao pad (fried rice)",
      ],
      dinner: [
        "Massaman curry with rice",
        "Pad kra pao (basil stir-fry)",
        "Larb gai with sticky rice",
        "Tom kha gai",
      ],
      snack: [
        "Mango sticky rice",
        "Fresh spring rolls",
        "Satay with peanut sauce",
      ],
    },
  },
  {
    id: "korea",
    name: "South Korea",
    flag: "🇰🇷",
    region: "asia",
    typicalIngredients: [
      "rice",
      "gochujang",
      "kimchi",
      "sesame oil",
      "garlic",
      "soy sauce",
      "tofu",
      "beef",
      "green onion",
      "eggs",
      "seaweed",
      "doenjang",
    ],
    mealPatterns: {
      breakfast: [
        "Rice with doenjang jjigae and banchan",
        "Gyeran-bap (egg rice)",
        "Hobak-juk (pumpkin porridge)",
      ],
      lunch: [
        "Bibimbap with gochujang",
        "Kimchi jjigae with rice",
        "Bulgogi with lettuce wraps",
        "Japchae with rice",
      ],
      dinner: [
        "Samgyeopsal with ssamjang",
        "Sundubu-jjigae",
        "Galbi-jjim (braised short ribs)",
        "Tteokbokki with fish cakes",
      ],
      snack: [
        "Kimbap rolls",
        "Hotteok (sweet pancake)",
        "Tteok (rice cakes)",
      ],
    },
  },

  // ─── Middle East ────────────────────────────────────────────
  {
    id: "lebanon",
    name: "Lebanon",
    flag: "🇱🇧",
    region: "middle_east",
    typicalIngredients: [
      "chickpeas",
      "tahini",
      "olive oil",
      "lemon",
      "garlic",
      "parsley",
      "pita bread",
      "lamb",
      "chicken",
      "bulgur",
      "yogurt",
      "sumac",
    ],
    mealPatterns: {
      breakfast: [
        "Manakish with zaatar",
        "Labneh with olive oil and bread",
        "Foul mudammas",
        "Knafeh with cheese",
      ],
      lunch: [
        "Chicken shawarma with garlic sauce",
        "Kibbeh with tabbouleh",
        "Kafta with hummus and rice",
        "Fattoush salad with grilled halloumi",
      ],
      dinner: [
        "Grilled kebab with baba ganoush",
        "Moujadara (lentil rice)",
        "Shish taouk with toum",
      ],
      snack: [
        "Hummus with pita",
        "Falafel wrap",
        "Mixed nuts and dried fruits",
      ],
    },
  },
  {
    id: "turkey",
    name: "Turkey",
    flag: "🇹🇷",
    region: "middle_east",
    typicalIngredients: [
      "lamb",
      "chicken",
      "yogurt",
      "tomato",
      "eggplant",
      "bulgur",
      "lentils",
      "olive oil",
      "pepper paste",
      "onion",
      "garlic",
      "sumac",
    ],
    mealPatterns: {
      breakfast: [
        "Turkish breakfast spread (kahvaltı)",
        "Menemen (egg scramble)",
        "Simit with cheese and tea",
      ],
      lunch: [
        "İskender kebab",
        "Mercimek çorbası (lentil soup)",
        "Lahmacun with salad",
        "Pide with cheese and meat",
      ],
      dinner: [
        "Adana kebab with bulgur pilaf",
        "Karnıyarık (stuffed eggplant)",
        "Hünkar beğendi",
        "Mantı with yogurt",
      ],
      snack: [
        "Börek with cheese",
        "Simit",
        "Baklava with tea",
      ],
    },
  },

  // ─── Africa ─────────────────────────────────────────────────
  {
    id: "morocco",
    name: "Morocco",
    flag: "🇲🇦",
    region: "africa",
    typicalIngredients: [
      "couscous",
      "chicken",
      "lamb",
      "chickpeas",
      "cumin",
      "cinnamon",
      "saffron",
      "olive oil",
      "tomato",
      "onion",
      "preserved lemon",
      "almonds",
    ],
    mealPatterns: {
      breakfast: [
        "Msemen with honey and butter",
        "Baghrir with olive oil",
        "Harcha with cheese and mint tea",
      ],
      lunch: [
        "Couscous with seven vegetables",
        "Chicken tagine with preserved lemon",
        "Lamb tagine with prunes",
        "Harira soup",
      ],
      dinner: [
        "Kefta tagine with eggs",
        "Pastilla with chicken",
        "Rfissa with lentils",
      ],
      snack: [
        "Chebakia",
        "Mint tea with almond cookies",
        "Dates with almonds",
      ],
    },
  },
  {
    id: "nigeria",
    name: "Nigeria",
    flag: "🇳🇬",
    region: "africa",
    typicalIngredients: [
      "yam",
      "cassava",
      "plantain",
      "palm oil",
      "scotch bonnet pepper",
      "tomato",
      "onion",
      "crayfish",
      "stockfish",
      "chicken",
      "beans",
      "rice",
    ],
    mealPatterns: {
      breakfast: [
        "Akara with pap (ogi)",
        "Yam and egg sauce",
        "Moi moi with custard",
      ],
      lunch: [
        "Jollof rice with fried chicken",
        "Pounded yam with egusi soup",
        "Fried rice with peppered beef",
        "Ofada rice with ayamase sauce",
      ],
      dinner: [
        "Amala with ewedu and gbegiri",
        "Pepper soup with goat meat",
        "Plantain with beans porridge",
      ],
      snack: [
        "Puff puff",
        "Chin chin",
        "Roasted plantain with groundnuts",
      ],
    },
  },

  // ─── Oceania ────────────────────────────────────────────────
  {
    id: "australia",
    name: "Australia",
    flag: "🇦🇺",
    region: "oceania",
    typicalIngredients: [
      "lamb",
      "chicken",
      "beef",
      "eggs",
      "avocado",
      "sweet potato",
      "sourdough bread",
      "feta cheese",
      "spinach",
      "salmon",
      "macadamia nuts",
      "beetroot",
    ],
    mealPatterns: {
      breakfast: [
        "Smashed avo on sourdough with poached eggs",
        "Vegemite toast with scrambled eggs",
        "Acai bowl with granola",
        "Banana bread with ricotta",
      ],
      lunch: [
        "Chicken pesto wrap",
        "Barramundi with chips and salad",
        "Meat pie with tomato sauce",
        "Poke bowl with salmon",
      ],
      dinner: [
        "BBQ lamb chops with roasted vegetables",
        "Grilled kangaroo with sweet potato mash",
        "Thai-style chicken stir-fry",
        "Salmon with broccolini and quinoa",
      ],
      snack: [
        "Lamingtons",
        "Tim Tams",
        "Fruit and cheese platter",
      ],
    },
  },
];

/**
 * Find a cuisine configuration by country ID.
 */
export function getCuisineByCountry(
  countryId: string,
): CuisineCountry | undefined {
  return CUISINE_COUNTRIES.find((c) => c.id === countryId);
}

/**
 * Return all cuisines that belong to a given region.
 */
export function getCuisinesByRegion(region: CuisineRegion): CuisineCountry[] {
  return CUISINE_COUNTRIES.filter((c) => c.region === region);
}

/**
 * Return a deduplicated list of every region present in the database.
 */
export function getAllRegions(): CuisineRegion[] {
  const regionSet = new Set<CuisineRegion>(
    CUISINE_COUNTRIES.map((c) => c.region),
  );
  return Array.from(regionSet);
}
